#
# appveyor.yml
#
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Skipping commits affecting specific files (GitHub only).
skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - '*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  matrix:
    # Qt5.15 / VisualStudio 2017 64bit
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      INIT_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      QT_PATH:  C:\Qt\5.15\msvc2019_64

    # Qt6.2 / VisualStudio 2019 64bit
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      INIT_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      QT_PATH:  C:\Qt\6.3\msvc2019_64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf false

# to disable automatic builds
build: off

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: call "%INIT_BAT%" %VCVARARG%
  - cmd: set PATH=%QT_PATH%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: qmake CONFIG+=release
  - cmd: nmake
  - cmd: cpi.exe tests\helloworld.cpp
  - cmd: cpi.exe tests\sqrt.cpp 7
  - cmd: cpi.exe tests\fibonacci.cpp 10
