name: ActionsCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Homebrew
        run: brew install qt6
      - name: build
        run: |
          qmake CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10

  ci-ubuntu22-qt6-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends g++ make qmake6 qt6-base-dev qt6-base-dev-tools
      - name: build
        run: |
          qmake6 CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi concept_add.cpp
          ./cpi fibonacci.cpp 10
          ./cpi if_initializer.cpp
          ./cpi ranges.cpp
          ./cpi unique_ptr.cpp
          ./cpi helloworld.cpp
          ./cpi optional.cpp
          ./cpi sqrt.cpp 7
      - name: error tests
        run: |
          ./cpi error_code.cpp
        continue-on-error: true

  ci-ubuntu22-qt6-clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt purge -y gcc g++
          sudo apt-get install -y --no-install-recommends clang make qmake6 qt6-base-dev qt6-base-dev-tools
      - name: build
        run: |
          qmake6 -spec linux-clang CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi concept_add.cpp
          ./cpi fibonacci.cpp 10
          ./cpi if_initializer.cpp
          ./cpi ranges.cpp
          ./cpi unique_ptr.cpp
          ./cpi helloworld.cpp
          ./cpi optional.cpp
          ./cpi sqrt.cpp 7
      - name: error tests
        run: |
          ./cpi error_code.cpp
        continue-on-error: true

  ci-ubuntu20-qt5-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends g++ make qtbase5-dev qt5-default qt5-qmake
      - name: build
        run: |
          qmake CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi concept_add.cpp
          ./cpi fibonacci.cpp 10
          ./cpi if_initializer.cpp
          ./cpi ranges.cpp
          ./cpi unique_ptr.cpp
          ./cpi helloworld.cpp
          ./cpi optional.cpp
          ./cpi sqrt.cpp 7
      - name: error tests
        run: |
          ./cpi error_code.cpp
        continue-on-error: true

  ci-ubuntu20-qt5-clang:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt purge -y gcc g++
          sudo apt-get install -y --no-install-recommends clang make qtbase5-dev qt5-default qt5-qmake
      - name: build
        run: |
          qmake -spec linux-clang CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi concept_add.cpp
          ./cpi fibonacci.cpp 10
          ./cpi if_initializer.cpp
          ./cpi ranges.cpp
          ./cpi unique_ptr.cpp
          ./cpi helloworld.cpp
          ./cpi optional.cpp
          ./cpi sqrt.cpp 7
      - name: error tests
        run: |
          ./cpi error_code.cpp
        continue-on-error: true
